In [1]:
from src.si.neural_network.layers import Dense
from src.si.neural_network.nn import NN
from src.si.neural_network.sigmoid_activation import SigmoidActivation
from src.si.neural_network.soft_max_activation import SoftMaxActivation
from src.si.neural_network.relu_activation import ReLUActivation
from src.si.neural_network.linear_activation import LinearActivation

from src.si.data.dataset import Dataset
import numpy as np

In [2]:
x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([1,
              0,
              0,
              1])

dataset = Dataset(X=x, y=y, features=['x1', 'x2'], label='x1 XNOR x2')
dataset.print_dataframe()

x1  x2
1   0   0
0   0   1
0   1   0
1   1   1

In [3]:
l1_weight_matrix = np.array([[20, -20],
                             [20, -20]])

l1_bias = np.array([[-30, 10]])

layer1 = Dense(input_size=2, output_size=2)
layer1.weights = l1_weight_matrix
layer1.bias = l1_bias

# weights and bias for the 2nd layer

l2_weight_matrix = np.array([[20],
                             [20]])

l2_bias = np.array([[-10]])

layer2 = Dense(input_size=2, output_size=1)
layer2.weights = l2_weight_matrix
layer2.bias = l2_bias

In [4]:
layer1_sigmoid = SigmoidActivation()
layer2_sigmoid = SigmoidActivation()

# between layers, we have the layer activation
nn_model = NN(
    layers=[layer1, layer1_sigmoid, layer2, layer2_sigmoid]
)

In [5]:
nn_model.fit(dataset=dataset)

In [6]:
nn_model.predict(dataset=dataset)

array([[9.99954561e-01],
       [4.54803785e-05],
       [4.54803785e-05],
       [9.99954561e-01]])

## Ex.10 Avaliação

In [7]:
x_3 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_3 = np.random.randint(0, 2, size=(100, 1))  # labels for the 100 samples of random binary integers

dataset_3 = Dataset(x_3, y_3)

In [8]:
layer3_1 = Dense(input_size=32, output_size=32)
layer3_2 = Dense(input_size=32, output_size=16)
layer3_3 = Dense(input_size=16, output_size=1)  #if score is <0.5 the output is 0, and if score is >0.5 the output is 1

layer3_1activation = SigmoidActivation()
layer3_2activation = SigmoidActivation()
layer3_3activation= SigmoidActivation()

# between layers, we have the layer activation
nn_model3 = NN(
    layers=[layer3_1, layer3_1activation, layer3_2, layer3_2activation, layer3_3, layer3_3activation]
)

In [9]:
nn_model3.fit(dataset=dataset_3)

In [10]:
nn_model3.predict(dataset=dataset_3)[:10]

array([[0.49242084],
       [0.49242589],
       [0.49242025],
       [0.49242132],
       [0.49241914],
       [0.49242228],
       [0.49242101],
       [0.4924231 ],
       [0.49242327],
       [0.49242034]])

Classificação de um problema multiclass

In [11]:
# Create an adequate training dataset
x_4 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_4 = np.random.randint(0, 3, size=(100, 1))  # labels for the 100 samples with 3 different classes

dataset_4 = Dataset(x_4, y_4)

In [12]:
layer4_1 = Dense(input_size=32, output_size=32)
layer4_2 = Dense(input_size=32, output_size=16)
layer4_3 = Dense(input_size=16, output_size=3)  # will assign each output to the corresponding class according to the score

layer4_1activation = SigmoidActivation()
layer4_2activation= SigmoidActivation()
layer4_3activation = SoftMaxActivation()  # will assign a probability to each class that summed together will add up to 1

# between layers, we have the layer activation
nn_model4 = NN(
    layers=[layer4_1, layer4_1activation, layer4_2, layer4_2activation, layer4_3, layer4_3activation]
)

In [13]:
nn_model4.fit(dataset=dataset_4)

In [14]:
nn_model4.predict(dataset=dataset_4)[:10]

array([[0.3324728 , 0.33832527, 0.32920193],
       [0.33247027, 0.3383288 , 0.32920093],
       [0.33247258, 0.33832313, 0.3292043 ],
       [0.33247133, 0.33832635, 0.32920232],
       [0.33247093, 0.33833005, 0.32919903],
       [0.33247156, 0.33832601, 0.32920242],
       [0.33247033, 0.33832705, 0.32920262],
       [0.33246971, 0.33832381, 0.32920648],
       [0.33247191, 0.33832432, 0.32920376],
       [0.33246986, 0.33832746, 0.32920268]])

Problema de regressão

In [15]:
# Create an adequate training dataset
x_5 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_5 = np.random.randn(100, 1)  # labels for the 100 samples of random floats

dataset_5 = Dataset(x_5, y_5)

In [16]:
layer5_1 = Dense(input_size=32, output_size=32)
layer5_2 = Dense(input_size=32, output_size=16)
layer5_3 = Dense(input_size=16, output_size=1)  # returns a single continuous target for each sample

layer5_1activation = ReLUActivation()
layer5_2activation = ReLUActivation()
layer5_3activation = LinearActivation()  # returns a real values for our output

# between layers, we have the layer activation
nn_model5 = NN(
    layers=[layer5_1, layer5_1activation, layer5_2, layer5_2activation, layer5_3, layer5_3activation]
)

In [17]:
nn_model5.fit(dataset=dataset_5)

In [19]:
nn_model5.predict(dataset=dataset_5)[:10]

array([[-1.27727785e-06],
       [ 9.30894269e-05],
       [ 2.26287800e-05],
       [ 4.93581201e-05],
       [ 7.76152236e-05],
       [ 7.55063162e-05],
       [ 8.07808013e-05],
       [ 8.11248888e-05],
       [ 3.11254314e-05],
       [ 1.16520067e-04]])